# -*- coding: utf-8 -*-
"""Maze_Solver_A_Star@

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnL2UdL83om5hiqhSI5xnNQfHi3VXaA3
"""

print("Maze Solver using A* Search")
print("Project is ready!")

# Create the maze

maze = [
    ['S', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
    ['#', '#', '.', '#', '.', '#', '#', '#', '.', '.'],
    ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
    ['.', '#', '#', '#', '#', '#', '#', '.', '#', '.'],
    ['.', '.', '.', '.', '.', '.', '.', '.', '.', 'G']
]

# Display the maze
for row in maze:
    print(' '.join(row))

# A* Search Algorithm

import heapq

def heuristic(a, b):
    # Manhattan Distance
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def a_star(maze, start, goal):
    rows = len(maze)
    cols = len(maze[0])

    # Priority queue
    open_list = []
    heapq.heappush(open_list, (0, start))

    # Cost from start
    g_cost = {start: 0}

    # Store previous position
    parent = {start: None}

    while open_list:

        # Get the position with lowest priority
        _, current = heapq.heappop(open_list)

        # Goal reached
        if current == goal:
            path = []

            while current is not None:
                path.append(current)
                current = parent[current]

            path.reverse()
            return path

        row, col = current

        # Possible movements: up, down, left, right
        directions = [
            (-1, 0),
            (1, 0),
            (0, -1),
            (0, 1)
        ]

        for dr, dc in directions:

            new_row = row + dr
            new_col = col + dc

            # Check boundaries
            if new_row < 0 or new_row >= rows:
                continue

            if new_col < 0 or new_col >= cols:
                continue

            # Ignore walls
            if maze[new_row][new_col] == '#':
                continue

            neighbor = (new_row, new_col)

            # Calculate cost
            new_g_cost = g_cost[current] + 1

            if neighbor not in g_cost or new_g_cost < g_cost[neighbor]:

                g_cost[neighbor] = new_g_cost

                f_cost = new_g_cost + heuristic(neighbor, goal)

                heapq.heappush(open_list, (f_cost, neighbor))

                parent[neighbor] = current

    return None

# Find Start (S) and Goal (G)

start = None
goal = None

for r in range(len(maze)):
    for c in range(len(maze[0])):
        if maze[r][c] == 'S':
            start = (r, c)
        elif maze[r][c] == 'G':
            goal = (r, c)

print("Start:", start)
print("Goal:", goal)

# Find the shortest path

path = a_star(maze, start, goal)

if path:
    print("Path found!")
    print("Path length:", len(path) - 1)
    print("Path:", path)
else:
    print("No path found!")

# Display the shortest path in the maze

if path:
    for r, c in path:
        if maze[r][c] != 'S' and maze[r][c] != 'G':
            maze[r][c] = '*'

    print("Final Maze:")
    for row in maze:
        print(' '.join(row))

import matplotlib.pyplot as plt

# Create a visual representation of the maze

plt.figure(figsize=(10, 5))

for r in range(len(maze)):
    for c in range(len(maze[0])):

        if maze[r][c] == '#':
            plt.fill_between(
                [c, c + 1],
                [len(maze) - r - 1, len(maze) - r - 1],
                [len(maze) - r, len(maze) - r],
                color='black'
            )

        elif maze[r][c] == '*':
            plt.fill_between(
                [c, c + 1],
                [len(maze) - r - 1, len(maze) - r - 1],
                [len(maze) - r, len(maze) - r],
                color='yellow'
            )

        elif maze[r][c] == 'S':
            plt.fill_between(
                [c, c + 1],
                [len(maze) - r - 1, len(maze) - r - 1],
                [len(maze) - r, len(maze) - r],
                color='green'
            )

        elif maze[r][c] == 'G':
            plt.fill_between(
                [c, c + 1],
                [len(maze) - r - 1, len(maze) - r - 1],
                [len(maze) - r, len(maze) - r],
                color='red'
            )

plt.xlim(0, len(maze[0]))
plt.ylim(0, len(maze))
plt.xticks(range(len(maze[0]) + 1))
plt.yticks(range(len(maze) + 1))
plt.grid(True)

plt.title("Maze Solver using A* Search")
plt.xlabel("Columns")
plt.ylabel("Rows")

plt.show()

# Test an unreachable maze

unreachable_maze = [
    ['S', '.', '#', '.', '.', '.'],
    ['#', '.', '#', '#', '#', '.'],
    ['.', '.', '#', '.', '#', '.'],
    ['.', '#', '#', '.', '#', '.'],
    ['.', '.', '.', '.', '#', 'G']
]

# Find start and goal
start2 = None
goal2 = None

for r in range(len(unreachable_maze)):
    for c in range(len(unreachable_maze[0])):
        if unreachable_maze[r][c] == 'S':
            start2 = (r, c)
        elif unreachable_maze[r][c] == 'G':
            goal2 = (r, c)

# Run A* Search
path2 = a_star(unreachable_maze, start2, goal2)

if path2:
    print("Path found!")
    print("Path length:", len(path2) - 1)
else:
    print("No path found!")
    print("The goal is unreachable from the starting point.")

# ============================================
# Maze Solver using A* Search Algorithm
# ============================================

import heapq
import matplotlib.pyplot as plt


# -------------------------------
# 1. Create the Maze
# -------------------------------

maze = [
    ['S', '.', '.', '#', '.', '.', '.', '.', '.', '.'],
    ['#', '#', '.', '#', '.', '#', '#', '#', '.', '.'],
    ['.', '.', '.', '.', '.', '.', '.', '.', '.', '.'],
    ['.', '#', '#', '#', '#', '#', '#', '.', '#', '.'],
    ['.', '.', '.', '.', '.', '.', '.', '.', '.', 'G']
]


# -------------------------------
# 2. Manhattan Distance Heuristic
# -------------------------------

def heuristic(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


# -------------------------------
# 3. A* Search Algorithm
# -------------------------------

def a_star(maze, start, goal):

    rows = len(maze)
    cols = len(maze[0])

    # Priority queue
    open_list = []

    # Add starting point
    heapq.heappush(open_list, (0, start))

    # Cost from start
    g_cost = {start: 0}

    # Store parent nodes
    parent = {start: None}

    while open_list:

        # Select node with lowest f-cost
        _, current = heapq.heappop(open_list)

        # Goal reached
        if current == goal:

            path = []

            while current is not None:
                path.append(current)
                current = parent[current]

            path.reverse()
            return path

        row, col = current

        # Up, Down, Left, Right
        directions = [
            (-1, 0),
            (1, 0),
            (0, -1),
            (0, 1)
        ]

        for dr, dc in directions:

            new_row = row + dr
            new_col = col + dc

            # Check boundaries
            if new_row < 0 or new_row >= rows:
                continue

            if new_col < 0 or new_col >= cols:
                continue

            # Ignore walls
            if maze[new_row][new_col] == '#':
                continue

            neighbor = (new_row, new_col)

            # Calculate g-cost
            new_g_cost = g_cost[current] + 1

            if neighbor not in g_cost or new_g_cost < g_cost[neighbor]:

                g_cost[neighbor] = new_g_cost

                # f(n) = g(n) + h(n)
                f_cost = new_g_cost + heuristic(neighbor, goal)

                heapq.heappush(open_list, (f_cost, neighbor))

                parent[neighbor] = current

    # No path exists
    return None


# -------------------------------
# 4. Find Start and Goal
# -------------------------------

start = None
goal = None

for r in range(len(maze)):
    for c in range(len(maze[0])):

        if maze[r][c] == 'S':
            start = (r, c)

        elif maze[r][c] == 'G':
            goal = (r, c)


# -------------------------------
# 5. Run A* Search
# -------------------------------

path = a_star(maze, start, goal)


# -------------------------------
# 6. Display Result
# -------------------------------

print("===================================")
print("     A* MAZE SOLVER")
print("===================================")

print("Start:", start)
print("Goal :", goal)

if path:

    print("\nPath Found!")
    print("Path Length:", len(path) - 1)

    print("\nPath Coordinates:")
    print(path)

else:

    print("\nNo Path Found!")
    print("The goal is unreachable.")


# -------------------------------
# 7. Create Maze with Path
# -------------------------------

display_maze = [row.copy() for row in maze]

if path:

    for r, c in path:

        if display_maze[r][c] != 'S' and display_maze[r][c] != 'G':
            display_maze[r][c] = '*'


# Print final maze

print("\nFinal Maze:")

for row in display_maze:
    print(' '.join(row))


# -------------------------------
# 8. Visualize the Maze
# -------------------------------

plt.figure(figsize=(10, 5))

rows = len(display_maze)
cols = len(display_maze[0])

for r in range(rows):

    for c in range(cols):

        cell = display_maze[r][c]

        if cell == '#':
            plt.fill_between(
                [c, c + 1],
                [rows-r-1, rows-r-1],
                [rows-r, rows-r],
                color='black'
            )

        elif cell == '*':
            plt.fill_between(
                [c, c + 1],
                [rows-r-1, rows-r-1],
                [rows-r, rows-r],
                color='yellow'
            )

        elif cell == 'S':
            plt.fill_between(
                [c, c + 1],
                [rows-r-1, rows-r-1],
                [rows-r, rows-r],
                color='green'
            )

        elif cell == 'G':
            plt.fill_between(
                [c, c + 1],
                [rows-r-1, rows-r-1],
                [rows-r, rows-r],
                color='red'
            )

plt.xlim(0, cols)
plt.ylim(0, rows)

plt.xticks(range(cols + 1))
plt.yticks(range(rows + 1))

plt.grid(True)

plt.title("Maze Solver using A* Search")
plt.xlabel("Columns")
plt.ylabel("Rows")

plt.show()